[project]
name = "wcfm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.45.0",
    "furl>=2.1.3",
    "httpx>=0.28.1",
    "typer>=0.15.1",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
]
